[package]
name = "gtk-rust-template"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "#description#"
homepage = "#website#"
repository = "#repository#"
authors = ["#author#"]
publish = false

[features]
# default = ["development"]
development = []

[profile.release]
lto = true

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
relm4 = { version = "0.9.1", features = ["libadwaita", "gnome_47"] }
relm4-components = "0.9.1"
tracing = "0.1.41"
tracing-subscriber = "0.3"
eimzo = {path = "crates/eimzo"}
tokio = { version = "1.47.0", features = ["full"]}

[workspace]
members = [".", "e-helper"]
default-members = [".", "e-helper"]