name: Release test

on:
  push:
    branches: [ main, bahrom04 ]

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: EIMZOManager.flatpak
          manifest-path: ./build-aux/org.xinux.EIMZOManager.json
          cache-key: flatpak-builder-${{ github.sha }}